import Link from 'next/link';
const industries=[
  {name:'Service Businesses',text:'Websites, lead capture, booking, and customer-care automation.',image:'https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=900&q=80'},
  {name:'E-commerce',text:'Buyer support, order workflows, WhatsApp agents, and operations.',image:'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?auto=format&fit=crop&w=900&q=80'},
  {name:'Education',text:'School assistants, student experiences, portals, and information access.',image:'https://images.unsplash.com/photo-1523240795612-9a054b0db644?auto=format&fit=crop&w=900&q=80'},
  {name:'Healthcare',text:'Patient journeys, appointment workflows, and clinic operations.',image:'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=900&q=80'},
  {name:'Logistics',text:'Inventory, fleet visibility, delivery workflows, and control centers.',image:'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=900&q=80'},
  {name:'Real Estate',text:'Lead qualification, property matching, CRM, and viewing automation.',image:'https://images.unsplash.com/photo-1560518883-ce09059eeffa?auto=format&fit=crop&w=900&q=80'},
];
export default function Industries(){return <section className="py-24 md:py-32 bg-stone-900 text-white"><div className="max-w-7xl mx-auto px-6 md:px-12"><div className="flex flex-col md:flex-row md:items-end justify-between gap-6"><div><span className="text-xs font-bold uppercase tracking-widest text-brand-400">Industries We Serve</span><h2 className="mt-4 text-3xl md:text-5xl font-medium">Technology shaped around<br/><span className="font-serif italic text-stone-400">your operating reality</span></h2></div><Link href="/industries" className="text-sm font-semibold text-brand-400">View all industries →</Link></div><div className="mt-14 grid sm:grid-cols-2 lg:grid-cols-3 gap-5">{industries.map(item=><article key={item.name} className="group relative min-h-[300px] rounded-2xl overflow-hidden"><img src={item.image} alt={`${item.name} industry`} className="absolute inset-0 w-full h-full object-cover group-hover:scale-105 transition-transform duration-700"/><div className="absolute inset-0 bg-gradient-to-t from-black via-black/35 to-transparent"/><div className="absolute inset-x-0 bottom-0 p-7"><h3 className="text-xl font-medium">{item.name}</h3><p className="mt-2 text-sm text-stone-300 leading-relaxed">{item.text}</p></div></article>)}</div></div></section>}
