import type { Metadata } from 'next';
import Link from 'next/link';
import Navbar from '@/components/layout/Navbar';
import Footer from '@/components/layout/Footer';

export const metadata: Metadata = { title: 'Industries We Serve | ZaishTech Software House', description: 'Software, mobile, and AI solutions for service businesses, e-commerce, education, HR tech, healthcare, logistics, and real estate.' };

const industries = [
  { title:'Service Businesses', text:'Booking, lead management, customer care, websites, and daily operational automation.', image:'https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=1000&q=80', capabilities:['Lead generation','Customer chat','Booking flows'] },
  { title:'E-commerce', text:'Buyer support, WhatsApp journeys, ordering operations, and customer portals.', image:'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?auto=format&fit=crop&w=1000&q=80', capabilities:['WhatsApp agents','Order workflows','Support automation'] },
  { title:'Education', text:'School assistants, student experiences, information portals, and administration tools.', image:'https://images.unsplash.com/photo-1523240795612-9a054b0db644?auto=format&fit=crop&w=1000&q=80', capabilities:['School chatbots','Student portals','Knowledge access'] },
  { title:'HR Technology', text:'AI career tools, recruitment workflows, interviews, resumes, and candidate insights.', image:'https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&w=1000&q=80', capabilities:['AI interviews','Resume tools','Candidate insights'] },
  { title:'Healthcare', text:'Scheduling, patient journeys, clinic operations, and secure role-based portals.', image:'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=1000&q=80', capabilities:['Appointments','Patient portals','Clinic workflows'] },
  { title:'Logistics', text:'Inventory, delivery operations, fleet visibility, exceptions, and reporting dashboards.', image:'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=1000&q=80', capabilities:['Fleet visibility','Inventory','Operations dashboards'] },
  { title:'Real Estate', text:'Lead qualification, property matching, viewing workflows, and sales automation.', image:'https://images.unsplash.com/photo-1560518883-ce09059eeffa?auto=format&fit=crop&w=1000&q=80', capabilities:['Property CRM','Lead automation','Viewing flows'] },
  { title:'SaaS Startups', text:'MVP engineering, product design, APIs, subscriptions, and scalable foundations.', image:'https://images.unsplash.com/photo-1551434678-e076c223a692?auto=format&fit=crop&w=1000&q=80', capabilities:['MVP delivery','Product engineering','Scalable APIs'] },
];

export default function IndustriesPage(){return <main><Navbar/><section className="pt-36 pb-24 text-white bg-cover bg-center" style={{backgroundImage:"linear-gradient(rgba(28,25,23,.82),rgba(28,25,23,.82)),url('https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1800&q=85')"}}><div className="max-w-5xl mx-auto px-6"><span className="text-xs font-bold uppercase tracking-widest text-brand-400">Industries</span><h1 className="mt-4 text-4xl md:text-6xl font-medium">Domain-aware software,<br/><span className="font-serif italic text-stone-300">built around the workflow</span></h1><p className="mt-6 max-w-2xl text-stone-300">We learn how your team works before choosing screens, systems, or automation.</p></div></section><section className="py-24 bg-stone-50"><div className="max-w-7xl mx-auto px-6 md:px-12 grid md:grid-cols-2 gap-8">{industries.map(item=><article key={item.title} className="group bg-white border border-stone-200 rounded-3xl overflow-hidden hover:-translate-y-1 hover:shadow-2xl transition-all duration-500"><div className="relative aspect-[16/9] overflow-hidden"><img src={item.image} alt={`${item.title} industry`} className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-700"/><div className="absolute inset-0 bg-gradient-to-t from-black/65 to-transparent"/><h2 className="absolute bottom-0 p-7 text-2xl md:text-3xl font-medium text-white">{item.title}</h2></div><div className="p-7 md:p-8"><p className="text-stone-600 leading-relaxed">{item.text}</p><div className="mt-6 flex flex-wrap gap-2">{item.capabilities.map(capability=><span key={capability} className="text-xs bg-stone-100 border border-stone-200 rounded-full px-3 py-1.5 text-stone-600">{capability}</span>)}</div><Link href="/contact" className="inline-flex items-center gap-2 mt-7 text-sm font-semibold text-brand-600 group-hover:gap-3 transition-all">Discuss a solution <span>→</span></Link></div></article>)}</div></section><section className="py-20 bg-stone-900 text-white text-center"><div className="max-w-3xl mx-auto px-6"><h2 className="text-3xl md:text-4xl font-medium">Your industry is not on the list?</h2><p className="mt-4 text-stone-400">If there is a clear workflow, customer problem, or operational bottleneck, we can explore it.</p><Link href="/contact" className="inline-block mt-8 bg-brand-600 px-7 py-3.5 rounded-full text-sm font-semibold">Tell us about your business</Link></div></section><Footer/></main>}
