export type ProjectStatus = 'Live' | 'Product' | 'In Development' | 'Concept Project';
export type PortfolioProject = { slug: string; title: string; summary: string; industry: string; service: string; status: ProjectStatus; tech: string[]; url?: string; challenge: string; solution: string };

export const portfolioProjects: PortfolioProject[] = [
  { slug: 'lucky-crystal-maids', title: 'Lucky Crystal Maids', summary: 'A service website and customer-care chatbot designed to help a cleaning company answer inquiries and convert visitors into leads.', industry: 'Cleaning Services', service: 'Web Development + AI Chatbot', status: 'Live', tech: ['React', 'Express.js', 'MongoDB'], url: 'https://luckycrystalmaids.com', challenge: 'Create a credible digital presence and make customer support easier for a service business.', solution: 'A responsive customer-facing website paired with a chatbot that supports common service and inquiry journeys.' },
  { slug: 'byt-cleaning-services', title: 'BYT Cleaning Services', summary: 'A modern cleaning-services website for the UAE market, structured around service discovery, content, and customer inquiries.', industry: 'Cleaning Services', service: 'Website Development', status: 'Live', tech: ['React', 'Express.js', 'MongoDB'], url: 'https://bytclean.ae', challenge: 'Present a broad service catalogue clearly and create useful paths from search traffic to customer contact.', solution: 'A responsive service platform with dedicated service content, blog publishing, and conversion-focused contact paths.' },
  { slug: 'hirely-ai-career-platform', title: 'Hirely AI Career Platform', summary: 'A React Native career app for AI mock interviews, ATS-friendly resume creation, and intelligent CV analysis.', industry: 'HR Technology', service: 'Mobile App + AI', status: 'Product', tech: ['React Native', 'Express.js', 'AI'], challenge: 'Give job seekers practical tools to prepare for role-specific interviews and improve their resumes.', solution: 'A mobile-first AI platform combining mock interview practice, resume building, and actionable CV feedback.' },
  { slug: 'ecommerce-whatsapp-automation', title: 'E-commerce WhatsApp Automation', summary: 'A private-client WhatsApp auto-reply workflow that helps an e-commerce team manage buyer conversations efficiently.', industry: 'E-commerce', service: 'WhatsApp Automation', status: 'Live', tech: ['WhatsApp', 'Express.js', 'Automation'], challenge: 'Reduce repetitive buyer support work while keeping customer conversations responsive.', solution: 'Automated reply and inquiry-handling flows designed around common buyer questions and operational needs.' },
  { slug: 'whatsapp-booking-agent', title: 'WhatsApp Booking Agent', summary: 'An intelligent conversational booking workflow being developed for an e-commerce business.', industry: 'E-commerce', service: 'AI Agent', status: 'In Development', tech: ['WhatsApp', 'AI', 'Express.js'], challenge: 'Turn customer conversations into structured bookings without adding manual coordination.', solution: 'A guided WhatsApp agent for availability, booking details, confirmations, and follow-up.' },
  { slug: 'school-support-chatbot', title: 'School Support Chatbot', summary: 'A school chatbot in development for answering common questions and improving access to information.', industry: 'Education', service: 'AI Chatbot', status: 'In Development', tech: ['AI', 'Chatbot', 'Knowledge Base'], challenge: 'Help students and parents find routine information without waiting for administrative support.', solution: 'A school-focused conversational assistant grounded in approved institutional information.' },
  { slug: 'clinic-operations-portal', title: 'Clinic Operations Portal', summary: 'A concept for appointments, patient workflows, staff coordination, and operational reporting.', industry: 'Healthcare', service: 'Concept: Custom Software', status: 'Concept Project', tech: ['Next.js', 'Node.js', 'PostgreSQL'], challenge: 'Demonstrate how fragmented clinic workflows can be unified.', solution: 'A role-based portal concept for scheduling, records, and operational visibility.' },
  { slug: 'fleet-control-center', title: 'Fleet Control Center', summary: 'A logistics concept for fleet visibility, delivery status, driver workflows, and exception management.', industry: 'Logistics', service: 'Concept: Operations Platform', status: 'Concept Project', tech: ['React', 'Maps', 'Node.js'], challenge: 'Demonstrate real-time coordination across vehicles and deliveries.', solution: 'A control-center concept bringing dispatch, alerts, and performance data into one interface.' },
  { slug: 'property-lead-platform', title: 'Property Lead Platform', summary: 'A real-estate concept combining lead capture, qualification, inventory matching, and viewing coordination.', industry: 'Real Estate', service: 'Concept: CRM + Automation', status: 'Concept Project', tech: ['Next.js', 'AI', 'MongoDB'], challenge: 'Show how property teams can respond faster to high volumes of leads.', solution: 'A focused CRM concept with automated qualification and property matching.' },
];
export const realProjects = portfolioProjects.filter((project) => project.status !== 'Concept Project');

export const projectImages: Record<string, string> = {
  'lucky-crystal-maids': 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=1200&q=80',
  'byt-cleaning-services': 'https://images.unsplash.com/photo-1527515637462-cff94eecc1ac?auto=format&fit=crop&w=1200&q=80',
  'hirely-ai-career-platform': 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1200&q=80',
  'ecommerce-whatsapp-automation': 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?auto=format&fit=crop&w=1200&q=80',
  'whatsapp-booking-agent': 'https://images.unsplash.com/photo-1556740758-90de374c12ad?auto=format&fit=crop&w=1200&q=80',
  'school-support-chatbot': 'https://images.unsplash.com/photo-1523240795612-9a054b0db644?auto=format&fit=crop&w=1200&q=80',
  'clinic-operations-portal': 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=1200&q=80',
  'fleet-control-center': 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=1200&q=80',
  'property-lead-platform': 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?auto=format&fit=crop&w=1200&q=80',
};
